### ISSUE TITLE
Mount Ordeals not working

### ISSUE THREAD

**Issue by tdYAMa7u** [OverlayPlugin/cactbot#68] opened 2024-02-21 02:51 UTC
Cleaves in Mount Ordeals normal not working for long time, usually it just says cone from ???
I suggest do some changes in this:
First two cleaves always static, i think its better to call something like "be at side of outer line"
And every other calls like just "stand max melee on yellow line"

**Comment by wexxlee** [comment] 2024-02-21 03:04
> Cleaves in Mount Ordeals normal not working for long time, usually it just says cone from ??? I suggest do some changes in this: First two cleaves always static, i think its better to call something like "be at side of outer line" And every other calls like just "stand max melee on yellow line"

Thanks for reporting.  Could you do two things so we can look at this further?

1.  With ACT and FFXIV running, in ACT:  go to Plugins -> OverlayPlugin.dll -> General and hit "Copy Tech Support Info to Clipboard", then reply and paste it here.  It will likely include your windows username in the various file paths (assuming you're on Windows) - e.g. "C:\Users\<username>\AppData..." - so feel free to replace that with something like "xx".

2.  Attach a log of the fight where this occurred.  Use the [Log Splitter](https://overlayplugin.github.io/cactbot/util/logtools/splitter.html), drop your log file where indicated, check "Anonymize Log", check the box for a fight where this occurred, hit "Export", and attach it to your reply.

Thanks.

**Comment by wexxlee** [comment] 2024-02-21 03:53
@tdYAMa7u You don't seem to have any overlays installed.  I'm not sure if you removed them prior to pasting this info (and I'm also not sure how you would be seeing cactbot alerts at all without having a raidboss overlay installed).

Your log doesn't include any MapEffect lines, which is why Mount Ordeals (and any other content that relies on MapEffect lines) is behaving abnormally.  Can you restart ACT, then go to Plugins -> OverlayPlugin.dll, and copy/paste the log from the bottom of the window here?

**Comment by xiashtra** [comment] 2024-02-21 06:10
> ```
> CactbotOverlay.dll   True    0.31.2.0 C:\Users\meow\AppData\Roaming\Advanced Combat Tracker\Plugins\cactbot-0.22.5\cactbot\CactbotOverlay.dll
> ```

You have a bad install path for Cactbot.

**Comment by xiashtra** [comment] 2024-02-21 07:08
> because....... i installed it many years ago and it have old path? i still have support for new duties like gilded araya, i mean, you can just queue for trial i said and check, its not new bug, it was here for like year, just check? sometimes callout do their job, but most of time its just cone from ???

Yes, you have an old path.  It may be causing a problem now, and you should fix it.

**Comment by wexxlee** [comment] 2024-02-21 07:37
> because....... i installed it many years ago and it have old path? i still have support for new duties like gilded araya, i mean, you can just queue for trial i said and check, its not new bug, it was here for like year, just check? sometimes callout do their job, but most of time its just cone from ???

I just ran it with no issues, and no one else has reported this problem.  Given the missing MapEffect lines in your log, it's definitely something about your particular install.  I would start with @xiashtra 's suggestion and doing a fresh install of ACT/OP/cactbot, and if that doesn't work, we can try to help you further.

**Comment by valarnin** [comment] 2024-03-02 18:45
@tdYAMa7u Is this issue still happening for you?

Given the state of the log file you uploaded, I believe that this is being caused by outdated/invalid opcodes. If you check the `Plugins` > `OverlayPlugin.dll` tab, at the bottom, there is a log window. I'm expecting that you'll see an error message something like one of the two following in there after starting ACT and the game:
```
No config opcode for game version 2024.02.05.0000.0000, opcode name MapEffect
No config opcodes for game version 2024.02.05.0000.0000
```

There may be other error messages there indicating the root cause of why the opcode is missing, e.g. a failure to fetch updated opcodes from the github repository.

**Comment by xiashtra** [comment] 2024-04-29 20:10
Since the original poster has not responded to requests for more information, I am closing this issue.  @tdYAMa7u if you are still having this problem, you can file another issue report.

**Closed by xiashtra** 2024-04-29 20:10 UTC
Labels: bug, pending info
