### ISSUE TITLE
Trigger of AbilityExtra cannot obtain the heading in matches

### ISSUE THREAD

**Issue by Souma-Sumire** [OverlayPlugin/cactbot#310] opened 2024-08-03 07:13 UTC
### What's your question?

Hello, I have a raidboss trigger like this:
```typescript
    {
      id: 'xxxx',
      type: 'AbilityExtra',
      netRegex: { 'id': '95C7' },
      run: (_data, matches) => {
        console.log(matches);
      },
    },
```
However, the heading attribute does not exist in matches (neither in the type hints nor in the actual object).
![image](https://github.com/user-attachments/assets/a5157746-8165-48ca-b355-c8dc1f2c3128)

whereas the log contains: `[06:27:48.055] 264 108:40013385:95C7:00013ED8:1:0.000:0.000:0.000:2.356`.

Is this a bug or a feature? Thank you in advance for your assistance.

**Comment by wexxlee** [comment] 2024-08-03 08:39
> Is this a bug or a feature? Thank you in advance for your assistance.

Bug.  Looks like the same root cause as the issue I fixed inn #265 - the field is defined as optional so not included in capture regex.  Will PR a fix for this tomorrow.

**Closed** 2024-08-03 17:57 UTC
Labels: bug, fix-me
