### ISSUE TITLE
E8S Mirror Mirror 3 sometimes does wrong directions

### ISSUE THREAD

**Issue by Stealth3si** [OverlayPlugin/cactbot#69] opened 2024-02-22 21:09 UTC
I was asked to submit this here instead by [quisquous](https://github.com/quisquous/cactbot/issues/6073#issuecomment-1960084642)

![image](https://github.com/quisquous/cactbot/assets/76997301/c3cd9f93-25f1-41fe-b39e-ef5ea92d8ae7)
![image](https://github.com/quisquous/cactbot/assets/76997301/6c1d259e-f142-4716-b0e5-dc40231fe619)
![image](https://github.com/quisquous/cactbot/assets/76997301/57c9433c-0193-4268-a948-4a9d3f0a9242)
![image](https://github.com/quisquous/cactbot/assets/76997301/4504e148-4695-40b5-a333-4c6175b219c0)

**Comment by valarnin** [comment] 2024-02-23 00:24
I'm going to quote wexxlee here (maybe we should have an issue template that asks for this info?)

1. With ACT and FFXIV running, in ACT:  go to Plugins -> OverlayPlugin.dll -> General and hit "Copy Tech Support Info to Clipboard", then reply and paste it here.  It will likely include your windows username in the various file paths (assuming you're on Windows) - e.g. "C:\Users<username>\AppData..." - so feel free to replace that with something like "xx".

2. Attach a log of the fight where this occurred.  Use the [Log Splitter](https://overlayplugin.github.io/cactbot/util/logtools/splitter.html), drop your log file where indicated, check "Anonymize Log", check the box for a fight where this occurred, hit "Export", and attach it to your reply.

(I vaguely recall something like this happening while running this for mount farm in December but it didn't really matter because we were doing it unsynced and just steamrolled it even with the damage downs, so I didn't bother reporting it)

**Comment by wexxlee** [comment] 2024-02-23 00:51
> I'm going to quote wexxlee here (maybe we should have an issue template that asks for this info?)

(Yeah, I was thinking something similar.  There's also some nice stuff with GitHub actions - auto-tagging, closing stale issues, etc. -that I think would be worth looking at too.  Adding to my list. 😄)

> (I vaguely recall something like this happening while running this for mount farm in December but it didn't really matter because we were doing it unsynced and just steamrolled it even with the damage downs, so I didn't bother reporting it)

I vaguely remember seeing something similar under the same conditions (and not reporting it either).  There's some comments in `e8s.ts` about some MapEffect locs that may or may not be right, so that may be one potential place to start.

A log that corresponds to the screenshots, as well as either the actual mirror placement during those screenshots (or, at a minimum, the "safe quadrant" that cactbot should have called) would be extremely helpful.

**Comment by JLGarber** [comment] 2024-02-23 05:12
Is it possible there's a timing issue with the `getCombatants` call that populates her facing [here](https://github.com/OverlayPlugin/cactbot/blob/72aa4ba56523bd496ab1b3f51416bed0db47a514/ui/raidboss/data/05-shb/raid/e8s.ts#L856)? There shouldn't be, but if I'm reading the screenshots correctly, a mistake with her facing would cause the issues we're seeing here.

(I sort of wonder whether that `getCombatants` call is even necessary now, since we have better log line support for facing and positioning directly.)

**Comment by xiashtra** [comment] 2024-02-24 01:33
```
Inject and use Deucalion for network data       False
```

Intermittent problem could easily be dropped network packets.  You also have old install paths that could interfere with cleanly updating.

**Comment by Stealth3si** [comment] 2024-02-25 07:28
It seemed to have fixed the issue fn. Thanks!

If it happens again next week I will repost here.

**Comment by wexxlee** [comment] 2024-02-25 20:08
I took a look at the log and triggers, and I think @JLGarber is right - it looks like a facing issue.  The alerts in the screenshot would have been correct if Shiva was facing south, but she wasn't.  The trigger treats any `abs(heading)` between 3.0 and 3.14 as north, and anything else as south, so if the combatant data polling picked up Shiva's (non-north) heading before it was updated, that would explain it.

(Incidentally, running the log through raidemulator shows `combatantData` at the time of trigger execution with a heading of -2.22, but I don't recall how we simulate that from a log read -- I assume it's based on the most recent prior log line with combatant position data?)

It seems plausible that fixing the install paths and using deucalion could impact how quickly combatant data is updated, but since valarnin and I also remember something like this happening, it may also just be an intermittent issue (which, iirc, is not unheard of for combatantData).  Either way, this is probably still something that could be fixed.

**Comment by xiashtra** [comment] 2024-02-26 16:47
> I took a look at the log and triggers, and I think @JLGarber is right - it looks like a facing issue. The alerts in the screenshot would have been correct if Shiva was facing south, but she wasn't. The trigger treats any `abs(heading)` between 3.0 and 3.14 as north, and anything else as south, so if the combatant data polling picked up Shiva's (non-north) heading before it was updated, that would explain it.
> 
> (Incidentally, running the log through raidemulator shows `combatantData` at the time of trigger execution with a heading of -2.22, but I don't recall how we simulate that from a log read -- I assume it's based on the most recent prior log line with combatant position data?)
> 
> It seems plausible that fixing the install paths and using deucalion could impact how quickly combatant data is updated, but since valarnin and I also remember something like this happening, it may also just be an intermittent issue (which, iirc, is not unheard of for combatantData). Either way, this is probably still something that could be fixed.

She teleports mid, facing north, and [optionally] turns to face south while casting here; it's possible that the `combatantData` polling is happening while she's turning.

**Comment by valarnin** [comment] 2024-02-26 16:50
Adding `ActorMove` and `ActorSetPos` lines is on my TODO list for OverlayPlugin which may be a better solution for things like this (and UWU titan jumps) going forward. I'm not sure if it's better to adjust the `getCombatants` call here to be more delayed now and then re-adjust later, or if it's better to just wait for the new lines to be available.

Assuming that timing is the root cause, of course.

**Comment by wexxlee** [comment] 2024-03-10 21:03
> It seemed to have fixed the issue fn. Thanks!
> 
> If it happens again next week I will repost here.

@Stealth3si , just checking in.  Any further issues since changing your install path and enabling deucalion?

**Comment by xiashtra** [comment] 2024-04-29 20:11
Since the original poster has not responded with any further problems, I am closing this issue.  @Stealth3si if you are still having this problem, you can file another issue report.

**Closed by xiashtra** 2024-04-29 20:11 UTC
Labels: bug, fix-me
